#!/usr/bin/env python3
"""WRATH shareable report — render a run as a self-contained, styled HTML page.

The export bundle (Markdown) turned into one standalone dark-theme HTML document you can open in any
browser or send to a stakeholder — no server, no dependencies (mermaid is loaded from CDN for the
topology when online, with the source as a graceful fallback). Pure + deterministic — see
webui/test_share.py.

    to_html(rec) -> html string
"""
import html as _html
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import export_run  # noqa: E402


def _inline(s):
    s = _html.escape(s, quote=False)
    s = re.sub(r"`([^`]+)`", r"<code>\1</code>", s)
    s = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", s)
    s = re.sub(r"\[([^\]]+)\]\(([^)]+)\)",
               lambda m: f'<a href="{m.group(2).replace(chr(34), "%22")}" target="_blank" rel="noopener">{m.group(1)}</a>', s)
    return s


def md_to_html(src):
    lines = src.split("\n")
    out, i, n = [], 0, len(src.split("\n"))
    while i < n:
        ln = lines[i]
        if ln.startswith("```"):
            lang = ln[3:].strip().lower()
            buf = []
            i += 1
            while i < n and not lines[i].startswith("```"):
                buf.append(lines[i])
                i += 1
            i += 1
            raw = "\n".join(buf)
            if lang == "mermaid":
                out.append('<div class="mermaid">' + _html.escape(raw) + "</div>")
            else:
                out.append("<pre><code>" + _html.escape(raw) + "</code></pre>")
            continue
        m = re.match(r"(#{1,4})\s+(.*)", ln)
        if m:
            lv = min(len(m.group(1)), 3)
            out.append(f"<h{lv}>" + _inline(m.group(2)) + f"</h{lv}>")
            i += 1
            continue
        if ln.strip().startswith("|") and i + 1 < n and re.match(r"^\s*\|?[\s:|-]+\|?\s*$", lines[i + 1]):
            rows = []
            while i < n and lines[i].strip().startswith("|"):
                rows.append(lines[i])
                i += 1

            def cells(r):
                return [c.strip() for c in r.strip().strip("|").split("|")]

            t = "<table><thead><tr>" + "".join("<th>" + _inline(c) + "</th>" for c in cells(rows[0])) + "</tr></thead><tbody>"
            for r in rows[2:]:
                t += "<tr>" + "".join("<td>" + _inline(c) + "</td>" for c in cells(r)) + "</tr>"
            out.append(t + "</tbody></table>")
            continue
        if re.match(r"^\s*[-*]\s+", ln):
            items = []
            while i < n and re.match(r"^\s*[-*]\s+", lines[i]):
                items.append("<li>" + _inline(re.sub(r"^\s*[-*]\s+", "", lines[i])) + "</li>")
                i += 1
            out.append("<ul>" + "".join(items) + "</ul>")
            continue
        if ln.startswith(">"):
            out.append("<blockquote>" + _inline(ln.lstrip("> ")) + "</blockquote>")
            i += 1
            continue
        if ln.strip() == "":
            i += 1
            continue
        out.append("<p>" + _inline(ln) + "</p>")
        i += 1
    return "\n".join(out)


_CSS = """
:root{--ink:#eef2fb;--mut:#8a96b4;--ac:#6ea8ff;--ac2:#36e0c8;--brd:rgba(150,175,235,.14)}
*{box-sizing:border-box}body{margin:0;background:#0a1020;color:var(--ink);
 font:15px/1.6 system-ui,-apple-system,Segoe UI,Roboto,Arial}
.wrap{max-width:900px;margin:0 auto;padding:42px 26px 80px}
h1{font-size:24px;border-bottom:1px solid var(--brd);padding-bottom:14px}
h2{font-size:18px;margin-top:1.8em;color:#fff}h3{font-size:15px;color:var(--ac)}
a{color:var(--ac2)}code{background:rgba(0,0,0,.4);padding:1px 6px;border-radius:5px;font-size:.9em}
pre{background:rgba(0,0,0,.4);padding:13px;border-radius:10px;overflow:auto;border:1px solid var(--brd)}
pre code{background:none;padding:0}
table{border-collapse:collapse;width:100%;margin:.8em 0;font-size:.92em}
th,td{border:1px solid var(--brd);padding:8px 11px;text-align:left}th{background:rgba(255,255,255,.06)}
tr:nth-child(even) td{background:rgba(255,255,255,.02)}
blockquote{margin:.6em 0;padding:6px 13px;border-left:3px solid var(--ac);background:rgba(110,168,255,.07);
 color:var(--mut);border-radius:0 8px 8px 0}
.mermaid{background:rgba(255,255,255,.03);border:1px solid var(--brd);border-radius:12px;padding:14px;text-align:center}
.foot{margin-top:40px;padding-top:16px;border-top:1px solid var(--brd);color:var(--mut);font-size:12px}
"""

_TEMPLATE = """<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title>
<style>{css}</style></head><body><div class="wrap">{body}
<div class="foot">Generated by WRATH — Workbench for Reasoned Architecture, Testing &amp; Handover. \
Read-only shareable report.</div></div>
<script src="https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js" onerror="window.__nm=1"></script>
<script>try{{if(!window.__nm)mermaid.initialize({{startOnLoad:true,theme:'dark',themeVariables:{{lineColor:'#36e0c8'}}}});}}catch(e){{}}</script>
</body></html>"""


def to_html(rec):
    body = md_to_html(export_run.to_markdown(rec))
    title = "WRATH — " + (rec.get("problem", "run")[:70])
    return _TEMPLATE.format(title=_html.escape(title), css=_CSS, body=body)


if __name__ == "__main__":
    import json
    MEM = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "wrath", "memory", "runs")
    rid = sys.argv[1] if len(sys.argv) > 1 else None
    if rid:
        print(to_html(json.load(open(os.path.join(MEM, rid + ".json")))))
